### ISSUE TITLE
create organization if it doesn't exist yet for zstor create namespace command

### ISSUE THREAD

**Issue by GlenDC** [zero-os/0-stor#466]
Currently we assume that the given organization already exists, during the execution of the `zstor create namespace` command. However it could be useful to be able to provide the automated feature to create the organization should it not exist yet, this way, the user doesn't have to go to the website first to create the organization.

Perhaps this shouldn't be the default behavior, and instead be behind some `-f/--force` flag, not sure about this one. But I do know it is a feature that is pretty useful. Or perhaps we could put it behind a `y(es)/n(o)` question, and provide a `-y/--yes` flag, to answer all such questions as yes, should they arise.

We should probably also log an info-level log, describing we're creating the organization programmatically, if we do so, because it is missing.

**Comment by GlenDC** [comment]
@zaibon would be happy to hear your opinion about this one

**Comment by zaibon** [comment]
I think it's a good idea. If we can provide a full 0-stor experience without the need for the user to go to the IYO webstie at all it's a good idea.
CLient would still have to get an app ID and secret, but from there he can manage everything from the zstor CLI.

I don't have a problem of making this the default behavior even. Do we know if IYO allow this and what kind of rights it needs to create an organization ?

**Comment by GlenDC** [comment]
I think IYO allows it, there is definitely a function for available in the generated IYO client. I don't think any special permissions are needed.

The only problem is however that the userID is not known, as we use appID/appSecret, while this is required as part of the POST request (see `POST /organizations` in https://itsyou.online/apidocumentation).

Somehow we'll need to get to know the userID of the user. Getting that userID using the API isn't possible either i think, so it would be required somehow as a config param.

On top of that organizations can also be owned by an organization instead of a user I think, supporting that is however optional I suppose.

**Comment by GlenDC** [comment]
The error status code returned by `CreateNewSubOrganization (`POST /organization/{globalid}`) is a vague `403` (`Forbidden`) though, so doesn't really say it's because it's because the organization itself doesn't exist.

Even so, I guess in our code we can try to interpret it as a organization-not-exists error, create that organization and see if that fixes it. If however that does not fix it, than I suppose we should return the original 403 error (and cleanup the mess we made on the way?).

**Comment by lafont-e** [comment]
From what I know about 0-stor, you are entitled to do almost nothing without the app-id, app-secret keys on the config file of zstor, so the api access to IYO it's already there, we just need to verify in CreateNamespace if the organization (also defined in the config file of zstor) exists and create it in case it does not exist. From there the namespace can be created.
This also suggest that maybe organization should be another optional positional parameter or a Flag to override the organization name.

**Comment by GlenDC** [comment]
Yes, but see https://github.com/zero-os/0-stor/issues/466#issuecomment-357987736, @lafont-e...

> This also suggest that maybe organization should be another optional positional parameter or a Flag to override the organization name.

Perhaps, but many parameters will become flags/env-variables once we work on #422, so no need to start doing that for parameters one by one...

**Comment by lafont-e** [comment]
Done, (https://github.com/zero-os/0-stor/pull/473)

**Comment by GlenDC** [comment]
The issue will close automatically, if you use the correct keywords in a commit message or PR description. See for example https://github.com/blog/1386-closing-issues-via-commit-messages.

**Comment by GlenDC** [comment]
In this case, only once @zaibon or I merge your PR, and thus accept your solution, will this issue close.

**Comment by lafont-e** [comment]
The code in the feat-466 branch, does work for me
```
bin/zstor namespace create ns466a
INFO[0000] overwrote namespace config property to 'ns466a' (was: 'ns466') 
INFO[0000] namespace "ns466a" created                   
$ cat config.yaml 
iyo:
  organization: test466f
   ....
```
and the organization test466f was non existing before the zstor command , but they appeared after.

**Comment by GlenDC** [comment]
> the organization test466f was non existing before the zstor command , but they appeared after.

Weird it didn't work for me before, and it still doesn't work for me.

For me your solution returns an error due to a 400 BAD Request response, e.g.:

```
Error: creation of namespace "ka" failed: [Error] CreateNewOrganization code=400, err=Bad Request
```

However I found out why it doesn't work, and it kinda is my fault, even though it is due to some weird and undocumented restriction which makes that endpoint (POST `/organization`) return a BAD-REQUEST response in case the the organization's globalid is less than 3 characters. This does seem to be documented, but still seems to be random to me. Having some more information returned besides bad request would be nice too, but ok.

Either way, I tested now with a non-existing organization which globalid is 3 characters, and now it does work for me. So your solution as proposed in #482 seems to fix the issue indeed.
